add comment element
coders-camp-2021-best-team/Freeverse pull request #43
Opened 2022-01-22 13:55 UTC by Mariusz-web

2022-01-22 20:32 UTC, Veryyapeee requested changes

2022-01-22 20:32 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.jsx
> +    date: PropTypes.string.isRequired
that should be a date element, and we should convert that to proper string directly in the component,
for example here we will receive the UTC date format, and here we want to convert that for like 'HH:MM' format or smth

2022-01-22 20:32 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.jsx
> +import PropTypes from 'prop-types';
Tested this time? :D

2022-01-22 20:42 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.jsx
> +    commentText: PropTypes.string.isRequired,
also this prop should be just `children`

2022-01-22 20:44 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.scss
> +        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
variabless.scss :P

2022-01-22 20:44 UTC, Veryyapeee commented
I think that font size is too big on mobile

2022-01-23 18:05 UTC, Veryyapeee requested changes

2022-01-23 18:05 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.scss
> +@include for-phone-only {
On Main resposinve font change is handled, pull Main and you won't probably need these styles

2022-01-26 19:17 UTC, Veryyapeee requested changes

2022-01-26 19:17 UTC, Veryyapeee commented on src/components/atoms/Date/Date.jsx
> +    const formatedDate = dayjs(children).format(format);
Such a overkill, we should just create helper function to parse date which will accept the two parameters
date, format, with default format
and return formatted date, we really don't need the separate component for that, overkilllll

2022-01-26 19:17 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.scss
> +@include for-phone-only {
?? @Mariusz-web

2022-01-27 19:37 UTC, T0ffik approved these changes

2022-01-27 19:39 UTC, Veryyapeee requested changes

2022-01-27 19:39 UTC, Veryyapeee commented on src/components/molecules/Comment/Comment.jsx
> +                    <Text>{dateFormat(date)}</Text>
You don't need text inside text, what for?

2022-01-27 19:44 UTC, Veryyapeee commented on src/utils/format.js
> +export function dateFormat(date, format = 'DD MM YYYY hh:mm') {
Use arrow function

2022-01-27 19:50 UTC, Veryyapeee approved these changes

2022-01-27 20:18 UTC, merged