Issue 55 feat/app fortune cookie
coders-camp-2021-best-team/Freeverse pull request #70
Opened 2022-02-04 17:07 UTC by Mariusz-web

2022-02-04 21:52 UTC, Veryyapeee requested changes

2022-02-04 21:52 UTC, Veryyapeee commented on src/components/organisms/Header/Header.jsx
> +        const response = await fetch('/fortune/wisdom');
We have axios installed, use axios

2022-02-05 16:54 UTC, Mariusz-web commented
I used axios instead of fetch

2022-02-05 17:20 UTC, T0ffik requested changes

2022-02-05 17:20 UTC, T0ffik commented on src/components/organisms/Header/Header.jsx
> +                    onClick={handleOnCookieClick}
Looks like clicking on cookie do nothing

2022-02-05 17:20 UTC, T0ffik commented on src/components/organisms/MessageCollection/MessageCollection.jsx
> +import { MessageComponent } from '../../molecules';
Why you changed this?

2022-02-05 20:48 UTC, PoProstuMieciek requested changes

2022-02-05 20:48 UTC, PoProstuMieciek commented on package.json
> +    "proxy": "http://yerkee.com/api"
What is this for?

2022-02-05 20:48 UTC, PoProstuMieciek commented on src/components/organisms/Header/Header.jsx
> +                            <button
I believe that we have a custom Button component. You should use that instead

2022-02-05 21:21 UTC, Mariusz-web commented
I use Button component, how did you write @PoProstuMieciek

2022-02-05 21:23 UTC, PoProstuMieciek approved these changes

2022-02-05 22:06 UTC, Veryyapeee commented on src/components/organisms/Header/Header.jsx
> +const getRandomFortune = async () => {
That should be in separate file

2022-02-05 22:07 UTC, Veryyapeee commented on src/components/organisms/Header/Header.jsx
> +                            <Button
Imo we should use modal component since we have it and imo it would be good fit for that

2022-02-06 14:29 UTC, Veryyapeee commented
We have some conflicts in here, I can't actually log in, please be up to date with main

2022-02-06 15:06 UTC, Mariusz-web commented
done

2022-02-07 19:20 UTC, Veryyapeee requested changes

2022-02-07 19:20 UTC, Veryyapeee commented on package.json
> +    "proxy": "http://yerkee.com/api"
Does it work on deploy? I don't think so, the real solution is to allow for cross origin access in axios request header

2022-02-07 21:40 UTC, Mariusz-web commented
I can't go to deploy, but I changed

2022-02-07 21:49 UTC, Veryyapeee approved these changes

2022-02-07 21:50 UTC, T0ffik approved these changes

2022-02-07 21:52 UTC, merged