Issue 56 feat/create user profile screen
coders-camp-2021-best-team/Freeverse pull request #71
Opened 2022-02-05 01:29 UTC by N00BKU

2022-02-08 08:18 UTC, PoProstuMieciek requested changes
It doesn't work for me. I am running local webserver and trying to access [localhost:3000/profile/test](http://localhost:3000/profile/test).
It throws me a bunch of errors, nothing is rendered on the page.

Logs: [localhost-1644308154541.log](https://github.com/coders-camp-2021-best-team/Freeverse/files/8021937/localhost-1644308154541.log)

2022-02-08 08:50 UTC, PoProstuMieciek requested changes
You are using the hooks a bit wrong, but that's ok. I fixed some small bugs for you, because we have very little time before today's meeting.

2022-02-08 08:50 UTC, PoProstuMieciek commented on src/components/molecules/UserInfo/UserInfo.jsx
>                      className='atom__image'
I think that you changed the class name for image in SCSS, but forgot to change it also in the JSX component

2022-02-08 08:50 UTC, PoProstuMieciek commented on src/components/molecules/UserInfo/UserInfo.scss
> -    .atom__image {
here, the thing that you changed

2022-02-08 08:50 UTC, PoProstuMieciek commented on src/components/organisms/UserDetails/UserDetails.jsx
> +// import { Timestamp } from 'firebase/firestore'; TODAY'S DATE
```js
import { Timestamp } from 'firebase/firestore';
import PropTypes from 'prop-types';
import { InformationRow, Text } from '../..';
import { useUserDetails } from '../../../hooks';
import { dateFormat } from '../../../utils';

import './UserDetails.scss';

export const UserDetails = ({ userID }) => {
    const { data: userData } = useUserDetails(userID);

    if (!userData?.data()) {
        return null;
    }

    const { birthday, hobbies, city } = userData.data();

    let birthday_str = dateFormat(birthday?.toDate(), 'DD.MM.YYYY');
    const age = Timestamp.now() - birthday;
    const years_old = Math.floor(age / 60 / 60 / 24 / 365);
    birthday_str += ` (${years_old} yo)`;

    const hobbies_str = hobbies.join(', ');

    return (
        <div>
            <Text size='medium'>User Details</Text>

            <InformationRow iconName='birthday'>
                {birthday_str || 'Not available'}
            </InformationRow>

            <InformationRow iconName='home'>
                {city || 'Not available'}
            </InformationRow>

            <InformationRow iconName='googleController'>
                {hobbies_str || 'Not available'}
            </InformationRow>
        </div>
    );
};

UserDetails.propTypes = {
    userID: PropTypes.string.isRequired
};
```

2022-02-08 08:50 UTC, PoProstuMieciek commented on src/pages/Profile/Profile.jsx
> -import PropTypes from 'prop-types';
```js
import { useParams } from 'react-router';
import {
    ImageComponent,
    UserInfo,
    UserDetails,
    PostCollection,
    Text
} from '../../components';
import { useUserDetails } from '../../hooks';
import DEFAULT_BACKGROUND from '../../images/background.png';

import './Profile.scss';

export const ProfilePage = () => {
    const params = useParams();
    const userID = params.id;

    const { data: userData } = useUserDetails(userID);

    // TODO: wait for hooks at PR #82
    // const { data: postsData } = useUserPosts(userID);

    if (!userData?.data()) {
        return null;
    }

    const { background_picture_url } = userData.data();

    return (
        <div className='profile__page'>
            <div>
                <ImageComponent
                    customClass='background__image'
                    src={background_picture_url || DEFAULT_BACKGROUND}
                />
            </div>

            <UserInfo userID={userID} customClass='profile__page__user__info' />

            <UserDetails userID={userID} />

            <div>
                <Text size='medium'>Posts</Text>

                {/* TODO: posts */}
                <PostCollection userPosts={[]} />
            </div>
        </div>
    );
};
```

2022-02-10 12:47 UTC, PoProstuMieciek approved these changes
I added a slight change into styles myself (we have no time, sorry) because `Post` component styles were broken on `ProfileScreen`, but it is OK now.

2022-02-10 12:50 UTC, Mariusz-web approved these changes

2022-02-10 12:58 UTC, KonTra7cf approved these changes

2022-02-10 14:08 UTC, merged